### ISSUE TITLE
Can't set Python3 with installed RobotFramework as Installed framework for RED

### ISSUE THREAD

**Issue by filug** [nokia/RED#125]
**My setup**
- Eclipse: Oxygen Release (4.7.0)
- RED plugin: 0.7.9.2017062909 (installed via Marketplace)
- distro: Debian Stretch
- python3: 3.5.3
- robotframework: 3.0.2 (installed via pip3 install robotframework)

**Issue**
RED is not able to detect Python3 with robotframework as an interpreter.
Button `Window → Preferences → Robot Framework → Installed frameworks → Discover` is adding only the following item to the list

```
name: <unknown> path: /usr/bin
```

I have no idea how to force RED to use my configuration.

**More details & observations**

Commands `robot` or `pybot` are working correctly

```
$ robot --version
Robot Framework 3.0.2 (Python 3.5.3 on linux)
```

also from python3 I can import _robot_ package without any problems

```
$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import robot
>>> print(robot.__file__)
/usr/local/lib/python3.5/dist-packages/robot/__init__.py
```

When I install `robotframework` for Python2 (i.e. `pip install robotframework`) RED is working OK, only Python3 is affected.

**Comment by KrzysztofJozefowicz** [comment]
Hi
RED is looking for "python" executable in PATH and by whereis , I suppose your Pyt3 has symlink python3 under /usr/bin, Pyt2 is linked as plain "python". This is why it does not autodiscover Pyt3 environment.

You can manually add python folder by following path:
`Window → Preferences → Robot Framework → Installed frameworks → Add`

Alternatively, you can rename python to python2 and copy python3 to python in /usr/bin 

We will discuss internally if we could extend Python search to python3 executable also.

**Comment by filug** [comment]
@KrzysztofJozefowicz indeed it's working.

> You can manually add python folder by following path:
> `Window → Preferences → Robot Framework → Installed frameworks → Add`

Unfortunately because in this menu I can't add link to the binary (i.e. `/usr/bin/python3`) but only link to the directory (`/usr/bin/`) I've solved this problem in this way:

1. I've created `~/tools/red-workaround`,
2. with the symlink `~/tools/red-workaround/python` to the `/usr/bin/python3`,
3. and via menu `Window → Preferences → Robot Framework → Installed frameworks → Add`  directory `~/tools/red-workaround` was added to the RED.

With this configuration RED is working as expected, nevertheless workaround is quite annoying and must be executed by each developer manually, so

> We will discuss internally if we could extend Python search to python3 executable also.

would be a nice feature.

**Comment by KrzysztofJozefowicz** [comment]
Good, let's make it an enhancement to look for python2 and python3 apart from python. Untill python4, we will be covered.

**Comment by aks1589** [comment]
Thanks @filug and @KrzysztofJozefowicz !!

**Comment by osde8info** [comment]
thanks @filug the symlink python3 -> python workaround for the eclipse red python3 problem worked for me too but i had to ignore warnings about all librarys being broken and only after running my suite did all the warnings disappear

**Comment by luisxiaomai** [comment]
Hope Python search to python3 executable can be supported asap, it will help us a lot.

**Comment by michalanglart** [comment]
fixed in 0.8.5

**Comment by manosnoam** [comment]
Still seeing this error on 0.8.11 - when using Python 3.6 with robotframework 3:

![image](https://user-images.githubusercontent.com/9913945/55725227-eb4cc200-5a15-11e9-854f-3af8471e1b7e.png)

If switching to Python2, it's working fine.

**Comment by modrz** [comment]
Hi,

Can you check following commands in terminal?
```
python3
import robot
from robot import version
version.get_full_version()
```

**Comment by manosnoam** [comment]
It seems to happen due to multiple versions of python3, where the default (python 3.4) does not contain robot package, as I added robot to python36 only (pip3.6 install robotframework).

I fixed it by changing the default python3 from 3.4 to 3.6:

```
$ python3
    Python 3.4.9 (default, Aug 14 2018, 21:28:57)
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import robot
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named 'robot'

$ ls -lh /usr/bin/python3
   lrwxrwxrwx. 1 root root  9 Dec  5 16:35 /usr/bin/python3 -> python3.4

$ sudo mv /usr/bin/python3 /usr/bin/_python3
$ sudo cp /usr/bin/python3.6 /usr/bin/python3

$ python3
    Python 3.6.6 (default, Jan 26 2019, 16:53:05)
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import robot
    >>> from robot import version
    >>> version.get_full_version()
    '3.1.1 (Python 3.6.6 on linux)'
```

**Comment by Chandral** [comment]
Another workaround I found was to setup a virtualenv and set the path from there for your project. I know that's a stretch but wanted to mention it here just in case it is feasible for someone.
