### ISSUE TITLE
Does RED 0.8.1 support Eclipse 4.5?

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#165]
We are using Eclipse 4.5 with RED 0.8.0.

And we are failed to upgrade to 0.8.1,  does 0.8.1 still support Eclipse 4.5?
For some reason, we are not able to upgrade Eclipse for now.

**Comment by michalanglart** [comment]
Please take o look at #161 

0.8.1 started using Eclipse 4.7 API a bit accidentally, so it's not working with 4.5

**Comment by StefanRas** [comment]
I have the same problem with Eclipse 2019-9 (4-13) and RED 0.8.13

**Comment by michalanglart** [comment]
Hi,

RED 0.8.13 was released almost 2 months before Eclipse 2019-09 and it was not yet supported. This is described here: #324 and it will be solved in next version 0.8.14 which we are planning to release on monday/tuesday next week.

**Comment by StefanRas** [comment]
Hello Michael,

Thank you for the swift support. I am now using Eclipse 2019-06 and my problem is solved.

I now have another issue, I would like like to exclude some files from running and set the "exclude flag" in the project explorer.
As you can see in the picture attached, the test suite is still executed. Am I doing something wrong or could this be a bug?

Not sure if this is the way to go for these types of questions, but I thoght I give it a try. Please, tell me if I need to make a "issue" on github.

Regards,

Stefan Ras



________________________________
Van: michalanglart <notifications@github.com>
Verzonden: vrijdag 4 oktober 2019 11:12
Aan: nokia/RED <RED@noreply.github.com>
CC: StefanRas <stefan_ras@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nokia/RED] Does RED 0.8.1 support Eclipse 4.5? (#165)


Hi,

RED 0.8.13 was released almost 2 months before Eclipse 2019-09 and it was not yet supported. This is described here: #324<https://github.com/nokia/RED/issues/324> and it will be solved in next version 0.8.14 which we are planning to release on monday/tuesday next week.

**Comment by michalanglart** [comment]
Hello,

> As you can see in the picture attached

You forgot the picture :)

> Please, tell me if I need to make a "issue" on github

For now I can answer your question here but in general we prefer another issue since:
1. your question is not related to this issue
2. this isue is closed for almost 2 years now

**Comment by StefanRas** [comment]
Okay, Let's try it with an attachment first.

I am hesitating creating a new issue, without it being an issue, but just my inexperience 😉


________________________________
Van: michalanglart <notifications@github.com>
Verzonden: maandag 14 oktober 2019 08:51
Aan: nokia/RED <RED@noreply.github.com>
CC: StefanRas <stefan_ras@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nokia/RED] Does RED 0.8.1 support Eclipse 4.5? (#165)


Hello,

As you can see in the picture attached

You forgot the picture :)

Please, tell me if I need to make a "issue" on github

For now I can answer your question here but in general we prefer another issue since:

  1.  your question is not related to this issue
  2.  this isue is closed for almost 2 years now

**Comment by michalanglart** [comment]
> Okay, Let's try it with an attachment first.

Okay, where is it attached?

**Comment by StefanRas** [comment]
Uhhh, as an attachment in the e-mail?



________________________________
Van: michalanglart <notifications@github.com>
Verzonden: maandag 14 oktober 2019 10:30
Aan: nokia/RED <RED@noreply.github.com>
CC: StefanRas <stefan_ras@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nokia/RED] Does RED 0.8.1 support Eclipse 4.5? (#165)


Okay, Let's try it with an attachment first.

Okay, where is it attached?

**Comment by michalanglart** [comment]
Ok, now I can see that you are replying vie email. 

It looks like something is not working at GitHub: your email reply is processed and it can be visible at GitHub directly, but your attachement is not here. Please reply directly at GitHub and attach the file instead of replying via email.

**Comment by michalanglart** [comment]
Looking at this: https://github.blog/2011-03-10-reply-to-comments-from-email/ it seems that the email attachements are still ignored in 2019:

> Email attachments are currently ignored. There’s no place to upload assets to issues or comments anyway
